// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    let token = data.session?.access_token;

    // If supabase client hasn't hydrated yet, fall back to the local session stored in localStorage
    if (!token && typeof window !== 'undefined') {
      try {
        const raw = window.localStorage.getItem('kili_local_auth_session');
        if (raw) {
          const parsed = JSON.parse(raw);
          token = parsed?.access_token ?? token;
        }
      } catch (e) {
        // ignore
      }
    }

    const validJwt = typeof token === 'string' && token.split('.').length === 3;
    // Allow the local fallback token in development to be forwarded for serverFns
    const allowLocalToken = token === 'local-access-token';
    return next({
      headers: validJwt || allowLocalToken ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
