// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient, type Session, type User } from '@supabase/supabase-js';
import type { Database } from './types';

const LOCAL_USERS_KEY = 'kili_local_auth_users';
const LOCAL_USERS_META_KEY = 'kili_local_users_meta';
const LOCAL_SESSION_KEY = 'kili_local_auth_session';
const localAuthListeners = new Set<(event: string, session: Session | null) => void>();
let fallbackToLocal = false;
let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _fallbackSupabase: ReturnType<typeof createFallbackSupabaseClient> | undefined;
export const ADMIN_EMAIL = 'admin@market.com';
export const ADMIN_PASSWORD = 'admin001';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function shouldFallback(error: unknown, result: { error?: any } | null = null) {
  const messages = [
    'Failed to fetch',
    'Network request failed',
    'ERR_NAME_NOT_RESOLVED',
    'AuthRetryableFetchError',
  ];

  const rawMessage = result?.error?.message ?? (error instanceof Error ? error.message : '') ?? '';
  if (/Too Many Requests|rate limit/i.test(rawMessage)) {
    return false;
  }

  if (result?.error?.message) {
    return messages.some((message) => result.error.message.includes(message));
  }

  if (error instanceof Error) {
    return messages.some((message) => error.message.includes(message));
  }

  return false;
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    try {
      return await fetch(input, { ...init, headers });
    } catch (error) {
      fallbackToLocal = true;
      console.warn('[Supabase] Network fetch failed, switching to local auth fallback.', error);
      throw error;
    }
  };
}

function getBrowserStorageItem<T>(key: string): T | null {
  if (typeof window === 'undefined') return null;
  const item = window.localStorage.getItem(key);
  if (!item) return null;
  try {
    return JSON.parse(item) as T;
  } catch {
    return null;
  }
}

function setBrowserStorageItem<T>(key: string, value: T) {
  if (typeof window === 'undefined') return;
  window.localStorage.setItem(key, JSON.stringify(value));
}

function removeBrowserStorageItem(key: string) {
  if (typeof window === 'undefined') return;
  window.localStorage.removeItem(key);
}

function getLocalUsers(): Record<string, string> {
  return getBrowserStorageItem<Record<string, string>>(LOCAL_USERS_KEY) ?? {};
}

function setLocalUsers(users: Record<string, string>) {
  setBrowserStorageItem(LOCAL_USERS_KEY, users);
}

function getLocalUsersMeta(): Record<string, any> {
  return getBrowserStorageItem<Record<string, any>>(LOCAL_USERS_META_KEY) ?? {};
}

function setLocalUsersMeta(meta: Record<string, any>) {
  setBrowserStorageItem(LOCAL_USERS_META_KEY, meta);
}

const DEFAULT_LOCAL_USER_META = { balance: 500, subscribed: false, subscription_status: null, subscription_plan: null, locked: false, page_locks: {}, wallet_address: null };

export function getLocalUserMeta(email: string) {
  const meta = getLocalUsersMeta();
  return meta[email] ?? { ...DEFAULT_LOCAL_USER_META };
}

export function writeLocalUserMeta(email: string, changes: Record<string, any>) {
  const meta = getLocalUsersMeta();
  meta[email] = { ...(meta[email] ?? { ...DEFAULT_LOCAL_USER_META }), ...changes };
  setLocalUsersMeta(meta);
  if (typeof window !== "undefined") {
    window.dispatchEvent(new Event("kili-local-user-meta-updated"));
  }
}

export function getLocalSession(): Session | null {
  return getBrowserStorageItem<Session>(LOCAL_SESSION_KEY);
}

function setLocalSession(session: Session) {
  setBrowserStorageItem(LOCAL_SESSION_KEY, session);
  localAuthListeners.forEach((callback) => callback('SIGNED_IN', session));
}

function clearLocalSession() {
  removeBrowserStorageItem(LOCAL_SESSION_KEY);
  localAuthListeners.forEach((callback) => callback('SIGNED_OUT', null));
}

function createLocalUser(email: string, password: string) {
  const users = getLocalUsers();
  if (users[email]) {
    throw new Error('User already exists');
  }

  users[email] = password;
  setLocalUsers(users);
  writeLocalUserMeta(email, { ...DEFAULT_LOCAL_USER_META });

  const user: User = {
    id: `local-${email}`,
    app_metadata: {},
    user_metadata: {},
    aud: 'authenticated',
    email,
    role: 'authenticated',
    created_at: new Date().toISOString(),
  } as User;

  const session: Session = {
    access_token: 'local-access-token',
    token_type: 'bearer',
    expires_in: 3600,
    expires_at: Math.floor(Date.now() / 1000) + 3600,
    refresh_token: 'local-refresh-token',
    provider_token: null,
    user,
  } as Session;

  setLocalSession(session);
  return { user, session };
}

function signInLocalUser(email: string, password: string) {
  const users = getLocalUsers();
  const isAdminLogin = email === ADMIN_EMAIL && password === ADMIN_PASSWORD;

  if (!isAdminLogin && users[email] !== password) {
    return {
      data: { user: null, session: null },
      error: { message: 'Invalid email or password' },
    };
  }

  const user: User = {
    id: `local-${email}`,
    app_metadata: {},
    user_metadata: {},
    aud: 'authenticated',
    email,
    role: 'authenticated',
    created_at: new Date().toISOString(),
  } as User;

  const session: Session = {
    access_token: 'local-access-token',
    token_type: 'bearer',
    expires_in: 3600,
    expires_at: Math.floor(Date.now() / 1000) + 3600,
    refresh_token: 'local-refresh-token',
    provider_token: null,
    user,
  } as Session;

  setLocalSession(session);
  return { data: { user, session }, error: null };
}

function signUpLocalUser(email: string, password: string) {
  if (email === ADMIN_EMAIL && password === ADMIN_PASSWORD) {
    try {
      const { user, session } = createLocalUser(email, password);
      return { data: { user, session }, error: null };
    } catch {
      return signInLocalUser(email, password);
    }
  }

  try {
    const { user, session } = createLocalUser(email, password);
    return { data: { user, session }, error: null };
  } catch (error: unknown) {
    return {
      data: { user: null, session: null },
      error: error instanceof Error ? error : { message: 'Signup failed' },
    };
  }
}

function createFallbackSupabaseClient() {
  return {
    auth: {
      signInWithPassword: async ({ email, password }: { email: string; password: string }) => signInLocalUser(email, password),
      signUp: async ({ email, password }: { email: string; password: string }) => signUpLocalUser(email, password),
      getSession: async () => ({ data: { session: getLocalSession() }, error: null }),
      getUser: async () => ({ data: { user: getLocalSession()?.user ?? null }, error: null }),
      signOut: async () => {
        clearLocalSession();
        return { data: null, error: null };
      },
      onAuthStateChange: (callback: (event: string, session: Session | null) => void) => {
        localAuthListeners.add(callback);
        callback(getLocalSession() ? 'SIGNED_IN' : 'SIGNED_OUT', getLocalSession());
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                localAuthListeners.delete(callback);
              },
            },
          },
        };
      },
    },
    from: (_table: string) => {
      const chain: any = {
        select: async () => ({ data: [], error: null }),
        insert: async () => ({ data: null, error: null }),
        update: async () => ({ data: null, error: null }),
        delete: async () => ({ data: null, error: null }),
        maybeSingle: async () => ({ data: null, error: null }),
        single: async () => ({ data: null, error: null }),
        eq() {
          return this;
        },
        order() {
          return this;
        },
        limit() {
          return this;
        },
        range() {
          return this;
        },
        match() {
          return this;
        },
        returning() {
          return this;
        },
      };
      return chain;
    },
  } as any;
}

function createAuthWrapper(auth: any) {
  return {
    signInWithPassword: async (params: { email: string; password: string }) => {
      try {
        const result = await auth.signInWithPassword(params);
        if (shouldFallback(null, result)) {
          return signInLocalUser(params.email, params.password);
        }
        return result;
      } catch (error) {
        if (shouldFallback(error)) {
          return signInLocalUser(params.email, params.password);
        }
        throw error;
      }
    },
    signUp: async (params: { email: string; password: string }) => {
      try {
        const result = await auth.signUp(params);
        if (shouldFallback(null, result)) {
          return signUpLocalUser(params.email, params.password);
        }
        return result;
      } catch (error) {
        if (shouldFallback(error)) {
          return signUpLocalUser(params.email, params.password);
        }
        throw error;
      }
    },
    getSession: async () => {
      try {
        const result = await auth.getSession();
        if (shouldFallback(null, result)) {
          return { data: { session: getLocalSession() }, error: null };
        }
        return result;
      } catch (error) {
        if (shouldFallback(error)) {
          return { data: { session: getLocalSession() }, error: null };
        }
        throw error;
      }
    },
    getUser: async () => {
      try {
        const result = await auth.getUser();
        if (shouldFallback(null, result)) {
          return { data: { user: getLocalSession()?.user ?? null }, error: null };
        }
        return result;
      } catch (error) {
        if (shouldFallback(error)) {
          return { data: { user: getLocalSession()?.user ?? null }, error: null };
        }
        throw error;
      }
    },
    signOut: async () => {
      let actualResult: any = null;
      try {
        actualResult = await auth.signOut();
      } catch (error) {
        if (!shouldFallback(error)) {
          throw error;
        }
      }

      clearLocalSession();
      if (shouldFallback(null, actualResult)) {
        return { data: null, error: null };
      }
      return actualResult ?? { data: null, error: null };
    },
    onAuthStateChange: (...args: any[]) => {
      const callback = typeof args[0] === 'function' ? args[0] : args[1];
      const event = typeof args[0] === 'string' ? args[0] : undefined;
      let unsubscribeActual: (() => void) | undefined;

      if (!callback || typeof callback !== 'function') {
        return { data: { subscription: { unsubscribe: () => {} } } };
      }

      try {
        const result = event ? auth.onAuthStateChange(event, callback) : auth.onAuthStateChange(callback);
        unsubscribeActual = result?.data?.subscription?.unsubscribe;
      } catch {
        unsubscribeActual = undefined;
      }

      localAuthListeners.add(callback);
      const unsubscribe = () => {
        localAuthListeners.delete(callback);
        unsubscribeActual?.();
      };

      callback(getLocalSession() ? 'SIGNED_IN' : 'SIGNED_OUT', getLocalSession());
      return { data: { subscription: { unsubscribe } } };
    },
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Falling back to local auth mode.`;
    console.warn(`[Supabase] ${message}`);
    fallbackToLocal = true;
    return createFallbackSupabaseClient();
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });

  // Preserve the client prototype and methods like `from()` while wrapping auth.
  (client as any).auth = createAuthWrapper(client.auth);
  return client as unknown as ReturnType<typeof createSupabaseClient>;
}

function getSupabaseClient() {
  if (fallbackToLocal) {
    if (!_fallbackSupabase) {
      _fallbackSupabase = createFallbackSupabaseClient();
    }
    return _fallbackSupabase;
  }

  if (!_supabase) {
    _supabase = createSupabaseClient();
  }

  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export function isLocalMode() {
  const local = getLocalSession();
  return !isSupabaseConfigured || fallbackToLocal || !!local?.user?.id?.startsWith("local-");
}

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    return Reflect.get(getSupabaseClient(), prop, receiver);
  },
});

export function signInLocal(email: string, password: string) {
  return signInLocalUser(email, password);
}

export function signUpLocal(email: string, password: string) {
  return signUpLocalUser(email, password);
}

export const isSupabaseConfigured = Boolean(
  import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL,
) && Boolean(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY);

